version: 0.0
Resources:
  - lighthousechat-dev-hello:
      Type: "AWS::Lambda::Function"
      Properties:
        Name: "lighthousechat-dev-hello"
        Alias: "LATEST"
        CurrentVersion: "LATEST"
        TargetVersion: "LATEST"