version: 0.1
phases:
  install:
    commands:
      - npm install --global
      - pwd
      - mkdir -p ../github.com/thomasdane/lighthouseChat
      - mv * ../github.com/thomasdane/lighthouseChat
      - mv ../github.com .
      - cd github.com/thomasdane/lighthouseChat
      - pwd
      - ls
  build:
    commands:
      - make
  post_build:
    commands:
      - go test