version: 0.1
env:
  variables:
      PACKAGE: "github.com/thomasdane/lighthouseChat" 
phases:
  install:
    commands:
      - npm install -g serverless
      - pwd
      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - # Make sure we're in the package directort within our GOPATH
      - cd "/go/src/${PACKAGE}"
      - ls
  build:
    commands:
      - make
  post_build:
    commands:
      - go test