version: 0.1
variables: 
  GO111MODULE: "on"
phases:
  install:
    commands:
      - npm install --global
  build:
    commands:
      - env GOOS=linux go build -ldflags="-s -w" -o bin/hello hello/main.go
  post_build:
    commands:
      - go test