version: 0.1
variables: 
  GO111MODULE: "on"
  git-credential-helper: yes
runtime-versions:
  golang: 1.13
phases:
  install:
    commands:
      - npm install --global
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
      - echo Copying Source to Go module dir
      - ls -l $CODEBUILD_SRC_DIR
      - mkdir -p /go/src/github.com/thomasdane/lighthouseChat
      - cp -a $CODEBUILD_SRC_DIR/* /go/src/github.com/thomasdane/lighthouseChat
  build:
    commands:
      - mkdir -p bin
      - GOOS="linux" go build -ldflags="-s -w" -o bin/hello hello/main.go
  post_build:
    commands:
      - go test