version: 0.1
env:
  variables:
      PACKAGE: "github.com/thomasdane/lighthouseChat" 
phases:
  install:
    commands:
      - mkdir -p ${GOPATH}/src/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${GOPATH}/src/${PACKAGE}
      - npm install -g serverless
  build:
    commands:
      - cd ${GOPATH}/src/${PACKAGE}/hello && make
  post_build:
    commands:
      - cd hello && go test