version: 0.2
variables: 
  GO111MODULE: "on"
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - npm install --global
      - ls -l $CODEBUILD_SRC_DIR
      - mkdir -p /go/src/github.com/thomasdane/lighthouseChat
      - cp -a $CODEBUILD_SRC_DIR/* /go/src/github.com/thomasdane/lighthouseChat
  build:
    commands:
      - mkdir -p bin
      - GOOS="linux" go build -ldflags="-s -w" -o bin/hello hello/main.go
  post_build:
    commands:
      - cd hello
      - go test -v